" Set the Leader
let mapleader = "\<Space>"

" Set local leader 
let maplocalleader = "\<Space>"

" Backspace doesn't quite work on windows out of the box. 
set backspace=indent,eol,start

""""""""""""""""""""""""""""
" DISPLAY RELATED SETTINGS "
""""""""""""""""""""""""""""

" Syntax on
:syntax on

" Show Line Numbers
set number

" Status line
set laststatus=2

" Show me my position in the current document
set ruler

" Don't show relative line numbers
set relativenumber

" Support for 256-color scheme?
set termguicolors

" Indentation 
set autoindent
set smartindent

" Tabs and spaces
set tabstop=4
set softtabstop=4
" How many columns does the shift command indent
set shiftwidth=4
" I always want spaces, no tabs.
set expandtab
" Use shiftwidth to determine how many spaces to use
set smarttab

" File browser settings
set autochdir
let g:netrw_banner=0
let g:netrw_liststyle=1
let g:netrw_alto=1
let g:netrw_altv=1
let g:netrw_sort_by="exten"

""""""""""""""""""""""
" CUSTOM KEYBINDINGS "
""""""""""""""""""""""

" Disable the <esc> key in Input mode.
inoremap <C-c> <esc>
inoremap <esc> <nop>

" Change the omni key for ft_sql so it doesn't clash
let g:ftplugin_sql_omni_key = '<C-j>'

" Open the .vimrc flie from anywhere in normal mode
nnoremap <leader>ev :vsplit $MYVIMRC<cr>

" Source the .vimrc file from anywhere in normal mode
nnoremap <leader>sv :source $MYVIMRC<cr>

"""""""""""""""""
" AUTO COMMANDS "
"""""""""""""""""
augroup python_files
    "Autocommands for python
    autocmd!
    " Enable folding for python files
    autocmd FileType python :setlocal foldmethod=indent
    autocmd FileType python :setlocal foldlevel=99
    " PEP 8 tab/indentation
    autocmd FileType python :setlocal tabstop=4
    autocmd FileType python :setlocal softtabstop=4
    autocmd FileType python :setlocal shiftwidth=4
    autocmd FileType python :setlocal textwidth=100
    autocmd FileType python :setlocal expandtab
    autocmd FileType python :setlocal autoindent
    autocmd FileType python :setlocal fileformat=unix
augroup END

augroup rust_files
    "Autocommands for rust files
    autocmd!
    autocmd FileType rust :setlocal textwidth=100
augroup END

augroup javascript_files
    "Autocommands for javascript files
    autocmd!
    autocmd FileType javascript,json :setlocal tabstop=2
    autocmd FileType javascript,json :setlocal softtabstop=2
    autocmd FileType javascript,json :setlocal shiftwidth=2
    autocmd FileType javascript,json :setlocal expandtab
    autocmd FileType javascript,json :setlocal autoindent
    autocmd FileType javascript,json :setlocal textwidth=100
augroup END

augroup makefiles
    "Autocommands for makefiles
    autocmd!
    autocmd FileType make :setlocal noexpandtab
augroup END
