#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls -al --color=auto'
PS1='[\u@\h \W]\$ '

# Pulse audio doesn't start automatically for me :/
pulseaudio --start

# Firefox won't run without this for now
export MOZ_ENABLE_WAYLAND=1

# QT5 wayland support
export QT_QPA_PLATFORM=wayland-egl
