#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls -al --color=auto'
PS1='[\u@\h \W]\$ '

# Firefox won't run without this for now
export MOZ_ENABLE_WAYLAND=1
